name: Psscriptanalyzer

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
    paths-ignore:
      - '**.md'

  workflow_dispatch:

jobs:
  build:
    name: Psscriptanalyzer
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run PSScriptAnalyzer
        uses: JSChronicles/powershell-action@main
        with:
          recurse: true
          output: results.sarif
          enableExit: true
          excludeRule: '"PSAvoidDefaultValueForMandatoryParameter"'
